'use strict'
export default {
    SET_VALVE: 'SET_VALVE',
    TOGGLE_VALVE_START: 'TOGGLE_VALVE_START',
    TOGGLE_VALVE_FINISH: 'TOGGLE_VALVE_FINISH',
    GET_SCHEDULE_START: 'GET_SCHEDULE_START',
    GET_SCHEDULE_FINISH: 'GET_SCHEDULE_FINISH',
    ADD_TO_SCHEDULE_START: 'ADD_TO_SCHEDULE_START',
    ADD_TO_SCHEDULE_FINISH: 'ADD_TO_SCHEDULE_FINISH',
    REMOVE_FROM_SCHEDULE_START: 'REMOVE_FROM_SCHEDULE_START',
    REMOVE_FROM_SCHEDULE_FINISH: 'REMOVE_FROM_SCHEDULE_FINISH',
    GET_HISTORY_START: 'GET_HISTORY_START',
    GET_HISTORY_FINISH: 'GET_HISTORY_FINISH',
    UPDATE_HISTORY: 'UPDATE_HISTORY'
}
